function normalizePdfText(value) {
  return String(value || "")
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/\u00A0/g, " ")
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, "");
}

function escapePdfText(value) {
  return normalizePdfText(value).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function wrapText(text, maxLength = 88) {
  const words = normalizePdfText(text).split(/\s+/).filter(Boolean);
  const lines = [];
  let current = "";

  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length > maxLength && current) {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
  }

  if (current) lines.push(current);
  return lines.length ? lines : [""];
}

function addWrapped(lines, text, options = {}) {
  const { maxLength = 88, prefix = "" } = options;
  for (const line of wrapText(text, maxLength)) {
    lines.push(`${prefix}${line}`);
  }
}

function buildReportLines({ user, reading, report }) {
  const identity = report.identity || {};
  const hd = report.humanDesign?.summary || {};
  const sections = report.fullReport?.sections || [];
  const warnings = report.meta?.missingDataWarnings || [];

  const lines = [
    { text: "SHADOW CHART", size: 11, gap: 18 },
    { text: identity.title || "Full Birth Chart Report", size: 24, gap: 22 },
    { text: identity.subtitle || "Dark astrology birth chart reading", size: 13, gap: 18 },
    { text: `Prepared for: ${reading.firstName || user.name || user.email}`, size: 11 },
    { text: `Birth date: ${reading.birthDate || "Unknown"}`, size: 11 },
    { text: `Birth time: ${reading.birthTime || "Unknown"}`, size: 11 },
    { text: `Birth place: ${reading.birthPlace || "Unknown"}`, size: 11, gap: 18 },
  ];

  addWrapped(lines, identity.oneSentenceSummary || "", { maxLength: 82 });
  lines.push({ text: "", gap: 12 });

  if (warnings.length) {
    lines.push({ text: "DATA NOTES", size: 13, gap: 12 });
    warnings.forEach((warning) => addWrapped(lines, warning, { maxLength: 84, prefix: "- " }));
    lines.push({ text: "", gap: 12 });
  }

  lines.push({ text: "HUMAN DESIGN LAYER", size: 15, gap: 14 });
  [
    `Type: ${hd.type || "Pending"}`,
    `Strategy: ${hd.strategy || "Pending"}`,
    `Authority: ${hd.authority || "Pending"}`,
    `Profile: ${hd.profile || "Pending"}`,
    `Definition: ${hd.definition || "Pending"}`,
  ].forEach((line) => lines.push({ text: line, size: 11 }));
  addWrapped(lines, hd.interpretation || "", { maxLength: 84 });
  lines.push({ text: "", gap: 14 });

  lines.push({ text: "FULL REPORT", size: 15, gap: 14 });
  sections.forEach((section, index) => {
    lines.push({ text: `${index + 1}. ${section.title}`, size: 14, gap: 12 });
    addWrapped(lines, section.body, { maxLength: 86 });
    lines.push({ text: "", gap: 10 });
  });

  lines.push({ text: "Generated by Shadow Chart. This report is for reflection and entertainment, not medical, legal, or financial advice.", size: 9 });
  return lines;
}

function paginate(lines) {
  const pages = [];
  let page = [];
  let y = 736;

  for (const item of lines) {
    const size = item.size || 11;
    const gap = item.gap || Math.max(13, size + 3);
    if (y - gap < 56 && page.length) {
      pages.push(page);
      page = [];
      y = 736;
    }
    page.push({ ...item, y });
    y -= gap;
  }

  if (page.length) pages.push(page);
  return pages;
}

function createPdfBuffer(pages) {
  const objects = [];
  const addObject = (body) => {
    objects.push(body);
    return objects.length;
  };

  const catalogId = addObject("<< /Type /Catalog /Pages 2 0 R >>");
  const pagesId = addObject("");
  const fontId = addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  const pageIds = [];

  pages.forEach((page, index) => {
    const stream = [
      "BT",
      ...page.map((item) => {
        const size = item.size || 11;
        return `/F1 ${size} Tf 1 0 0 1 56 ${item.y} Tm (${escapePdfText(item.text)}) Tj`;
      }),
      `/F1 9 Tf 1 0 0 1 500 34 Tm (${index + 1}) Tj`,
      "ET",
    ].join("\n");
    const contentId = addObject(`<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}\nendstream`);
    const pageId = addObject(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`);
    pageIds.push(pageId);
  });

  objects[pagesId - 1] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageIds.length} >>`;

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((body, index) => {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let index = 1; index <= objects.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  return Buffer.from(pdf, "utf8");
}

function renderFullReportPdf({ user, reading, report }) {
  const lines = buildReportLines({ user, reading, report });
  return createPdfBuffer(paginate(lines));
}

module.exports = {
  renderFullReportPdf,
};
