function normalizePdfText(value) {
  return String(value || "")
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/\u00A0/g, " ")
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, "");
}

function escapePdfText(value) {
  return normalizePdfText(value).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function wrapText(text, maxLength = 88) {
  const words = normalizePdfText(text).split(/\s+/).filter(Boolean);
  const lines = [];
  let current = "";

  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length > maxLength && current) {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
  }

  if (current) lines.push(current);
  return lines.length ? lines : [""];
}

function addWrapped(lines, text, options = {}) {
  const { maxLength = 88, prefix = "", size = 11, gap } = options;
  for (const line of wrapText(text, maxLength)) {
    lines.push({
      text: `${prefix}${line}`,
      size,
      ...(gap ? { gap } : {}),
    });
  }
}

function buildReportLines({ user, reading, report }) {
  const identity = report.identity || {};
  const sections = report.fullReport?.sections || [];
  const warnings = report.meta?.missingDataWarnings || [];

  const lines = [
    { text: "SHADOW CHART", size: 11, gap: 18 },
    { text: identity.title || "Full Birth Chart Report", size: 24, gap: 22 },
    { text: identity.subtitle || "Dark astrology birth chart reading", size: 13, gap: 18 },
    { text: `Prepared for: ${reading.firstName || user.name || user.email}`, size: 11 },
    { text: `Birth date: ${reading.birthDate || "Unknown"}`, size: 11 },
    { text: `Birth time: ${reading.birthTime || "Unknown"}`, size: 11 },
    { text: `Birth place: ${reading.birthPlace || "Unknown"}`, size: 11, gap: 18 },
  ];

  addWrapped(lines, identity.oneSentenceSummary || "", { maxLength: 82 });
  lines.push({ text: "", gap: 12 });

  if (warnings.length) {
    lines.push({ text: "DATA NOTES", size: 13, gap: 12 });
    warnings.forEach((warning) => addWrapped(lines, warning, { maxLength: 84, prefix: "- " }));
    lines.push({ text: "", gap: 12 });
  }

  lines.push({ text: "FULL REPORT", size: 15, gap: 14 });
  sections.forEach((section, index) => {
    lines.push({ text: `${index + 1}. ${section.title}`, size: 14, gap: 12 });
    addWrapped(lines, section.body, { maxLength: 86 });
    lines.push({ text: "", gap: 10 });
  });

  lines.push({ text: "Generated by Shadow Chart. This report is for reflection and entertainment, not medical, legal, or financial advice.", size: 9 });
  return lines;
}

const ZODIAC_SIGNS = ["Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"];
const ZODIAC_LABELS = ["Ar", "Ta", "Ge", "Ca", "Le", "Vi", "Li", "Sc", "Sg", "Cp", "Aq", "Pi"];
const CHART_POINT_ORDER = [
  { key: "sun", label: "Sun", meaning: "Personality core, motivation, life-force" },
  { key: "moon", label: "Moon", meaning: "Emotional world, reactions, comfort zone" },
  { key: "ascendant", label: "Ascendant", meaning: "Social mask, first impression, behavioral style" },
  { key: "mercury", label: "Mercury", meaning: "Thinking, speech, perception" },
  { key: "venus", label: "Venus", meaning: "Love style, values, attraction" },
  { key: "mars", label: "Mars", meaning: "Drive, anger, action style" },
  { key: "jupiter", label: "Jupiter", meaning: "Growth, optimism, expansion" },
  { key: "saturn", label: "Saturn", meaning: "Boundaries, discipline, life lessons" },
  { key: "uranus", label: "Uranus", meaning: "Freedom, change, individuality" },
  { key: "neptune", label: "Neptune", meaning: "Dreams, sensitivity, idealization" },
  { key: "pluto", label: "Pluto", meaning: "Depth, power, transformation" },
];

function getChartPoints(chart) {
  return CHART_POINT_ORDER.map((point, index) => {
    const source = point.key === "ascendant" ? chart.ascendant : chart.planets?.[point.key];
    if (!source) return null;

    return {
      number: index + 1,
      label: point.label,
      meaning: point.meaning,
      longitude: source.longitude,
      sign: source.sign,
      degree: source.degree,
      house: source.house,
    };
  }).filter(Boolean);
}

function polarPoint(cx, cy, radius, longitude) {
  const angle = ((longitude - 90) * Math.PI) / 180;
  return {
    x: cx + Math.cos(angle) * radius,
    y: cy - Math.sin(angle) * radius,
  };
}

function pdfCircle(cx, cy, radius) {
  const c = radius * 0.5522847498;
  return [
    `${cx + radius} ${cy} m`,
    `${cx + radius} ${cy + c} ${cx + c} ${cy + radius} ${cx} ${cy + radius} c`,
    `${cx - c} ${cy + radius} ${cx - radius} ${cy + c} ${cx - radius} ${cy} c`,
    `${cx - radius} ${cy - c} ${cx - c} ${cy - radius} ${cx} ${cy - radius} c`,
    `${cx + c} ${cy - radius} ${cx + radius} ${cy - c} ${cx + radius} ${cy} c`,
  ].join("\n");
}

function lineCommand(a, b) {
  return `${a.x.toFixed(2)} ${a.y.toFixed(2)} m ${b.x.toFixed(2)} ${b.y.toFixed(2)} l S`;
}

function textCommand(text, x, y, size = 8) {
  return `BT /F1 ${size} Tf 1 0 0 1 ${x.toFixed(2)} ${y.toFixed(2)} Tm (${escapePdfText(text)}) Tj ET`;
}

function buildNatalWheelCommands(reading) {
  const chart = reading.chart || {};
  const planets = Object.values(chart.planets || {});
  if (!planets.length) return "";

  const chartPoints = getChartPoints(chart);
  const cx = 230;
  const cy = 390;
  const outer = 152;
  const signRing = 126;
  const planetRing = 88;
  const inner = 54;
  const ascendantLongitude = chart.ascendant?.longitude || 0;
  const commands = [
    "q",
    "0.05 0.045 0.055 rg 0.05 0.045 0.055 RG",
    pdfCircle(cx, cy, outer),
    "f",
    "0.72 0.58 0.34 RG 1.2 w",
    pdfCircle(cx, cy, outer),
    "S",
    "0.82 0.78 0.68 RG 0.65 w",
    pdfCircle(cx, cy, signRing),
    "S",
    "0.42 0.29 0.78 RG 0.55 w",
    pdfCircle(cx, cy, inner),
    "S",
  ];

  for (let index = 0; index < 12; index += 1) {
    const division = index * 30;
    commands.push("0.72 0.58 0.34 RG 0.35 w");
    commands.push(lineCommand(polarPoint(cx, cy, signRing, division), polarPoint(cx, cy, outer, division)));

    const house = ascendantLongitude + index * 30;
    commands.push("0.82 0.78 0.68 RG 0.25 w");
    commands.push(lineCommand(polarPoint(cx, cy, inner, house), polarPoint(cx, cy, signRing, house)));

    const labelPoint = polarPoint(cx, cy, outer - 24, division + 15);
    commands.push(textCommand(ZODIAC_LABELS[index], labelPoint.x - 5, labelPoint.y - 3, 8));
  }

  for (const aspect of (chart.aspects || []).slice(0, 18)) {
    const from = planets.find((planet) => planet.label === aspect.from);
    const to = planets.find((planet) => planet.label === aspect.to);
    if (!from || !to) continue;
    const color = aspect.type === "square" || aspect.type === "opposition" ? "0.70 0.08 0.10 RG" : "0.42 0.29 0.78 RG";
    commands.push(`${color} 0.35 w`);
    commands.push(lineCommand(polarPoint(cx, cy, planetRing, from.longitude), polarPoint(cx, cy, planetRing, to.longitude)));
  }

  chartPoints.forEach((chartPoint, index) => {
    const point = polarPoint(cx, cy, chartPoint.label === "Ascendant" ? signRing + 12 : planetRing - (index % 2) * 12, chartPoint.longitude);
    commands.push("0.06 0.055 0.06 rg 0.72 0.58 0.34 RG 0.8 w");
    commands.push(pdfCircle(point.x, point.y, 10));
    commands.push("B");
    commands.push(textCommand(String(chartPoint.number), point.x - 3, point.y - 3, 7));
  });

  commands.push(
    "0.72 0.58 0.34 RG 1 w",
    lineCommand(polarPoint(cx, cy, inner - 10, ascendantLongitude), polarPoint(cx, cy, outer + 8, ascendantLongitude)),
    textCommand("ASC", polarPoint(cx, cy, outer + 18, ascendantLongitude).x - 8, polarPoint(cx, cy, outer + 18, ascendantLongitude).y - 3, 8),
    "Q",
  );

  return commands.join("\n");
}

function buildCoverPage({ user, reading, report }) {
  const identity = report.identity || {};
  const chart = reading.chart || {};
  const legend = getChartPoints(chart).flatMap((point, index) => {
    const placement = `${point.degree ?? "?"} deg ${point.sign || "Unknown"}${point.house ? `, House ${point.house}` : ""}`;
    const y = 578 - index * 25;
    return [
      { text: `${point.number}. ${point.label} - ${placement}`, size: 7.5, x: 394, y },
      { text: point.meaning, size: 6.6, x: 406, y: y - 10 },
    ];
  });

  return [
    { text: "SHADOW CHART", size: 12, x: 56, y: 746 },
    { text: identity.title || "Full Birth Chart Report", size: 24, x: 56, y: 718 },
    { text: identity.subtitle || "Dark astrology birth chart reading", size: 13, x: 56, y: 696 },
    { text: "CHART LEGEND", size: 12, x: 394, y: 604 },
    ...legend,
    { kind: "raw", commands: buildNatalWheelCommands(reading) },
    { text: `Prepared for: ${reading.firstName || user.name || user.email}`, size: 10, x: 56, y: 116 },
    { text: `Birth date: ${reading.birthDate || "Unknown"}   Birth time: ${reading.birthTime || "Unknown"}   Birth place: ${reading.birthPlace || "Unknown"}`, size: 10, x: 56, y: 100 },
    { text: `Ascendant: ${chart.ascendant?.degree || "?"} deg ${chart.ascendant?.sign || "Unknown"}   Engine: ${chart.engine || "Shadow Chart"}`, size: 9, x: 56, y: 84 },
  ];
}

function paginate(lines) {
  const pages = [];
  let page = [];
  let y = 736;

  for (const item of lines) {
    const size = item.size || 11;
    const gap = item.gap || Math.max(13, size + 3);
    if (y - gap < 56 && page.length) {
      pages.push(page);
      page = [];
      y = 736;
    }
    page.push({ ...item, y });
    y -= gap;
  }

  if (page.length) pages.push(page);
  return pages;
}

function createPdfBuffer(pages) {
  const objects = [];
  const addObject = (body) => {
    objects.push(body);
    return objects.length;
  };

  const catalogId = addObject("<< /Type /Catalog /Pages 2 0 R >>");
  const pagesId = addObject("");
  const fontId = addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  const pageIds = [];

  pages.forEach((page, index) => {
    const stream = page
      .map((item) => {
        if (item.kind === "raw") return item.commands || "";
        const size = item.size || 11;
        const x = item.x || 56;
        return `BT /F1 ${size} Tf 1 0 0 1 ${x} ${item.y} Tm (${escapePdfText(item.text)}) Tj ET`;
      })
      .concat(`BT /F1 9 Tf 1 0 0 1 500 34 Tm (${index + 1}) Tj ET`)
      .join("\n");
    const contentId = addObject(`<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}\nendstream`);
    const pageId = addObject(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`);
    pageIds.push(pageId);
  });

  objects[pagesId - 1] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageIds.length} >>`;

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((body, index) => {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let index = 1; index <= objects.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  return Buffer.from(pdf, "utf8");
}

function renderFullReportPdf({ user, reading, report }) {
  const lines = buildReportLines({ user, reading, report });
  return createPdfBuffer([buildCoverPage({ user, reading, report }), ...paginate(lines)]);
}

module.exports = {
  renderFullReportPdf,
};
